export interface Reservation {
    checkIn: string ,
    checkOut: string ,
    rooms: string ,
    name: string ,
    lastName: string ,
    birthDate: string ,
    gender: string ,
    documentType: string ,
    documentId: string ,
    telephone: string ,
    email: string ,
    emergencyContact: string ,
    emergencyContactPhone: string ,
}